config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('marjoram.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),

    # Your stuff: custom urls includes go herep
    url(r'^o/', include('marjoram.orgapp.urls', namespace='orgapp')),
    url(r'^v/', include('marjoram.volapp.urls', namespace='volapp')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

marjoram/orgapp/urls.py
from django.conf.urls import include, url
from django.views.generic import TemplateView
from django.core.urlresolvers import reverse_lazy
from marjoram.orgapp.views import (
    index_view,
    dashboard_view,
    about_view,
    #messages,
    organizations,
)

urlpatterns = [
    url('^$', index_view, name='index'),
    url(r'^dashboard/$', dashboard_view, name='dashboard'),
    url(r'^about/$', about_view, name='about'),
]

# organizations
urlpatterns += [
    url(r'^organizations/filter/(?P<pk>\w+)/$', organizations.organization_detail_view, name='organization_profile'),
    url(r'^organizations/(?P<pk>\w+)/settings/$', organizations.organization_settings_view, name='organization_settings'),
    url(r'^organizations/(?P<pk>\w+)/contact/$', organizations.organization_contact_view, name='contact_organization'),
    url(r'^organizations/filter/$', organizations.organization_list_view, name="list_organization"),
    url(r'^organizations/create/$', organizations.organization_add_view, name='create_organization'),
]

marjoram/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

marjoram/volapp/urls.py
from django.conf.urls import url, include
from django.views.generic import TemplateView
from django.core.urlresolvers import reverse_lazy
from marjoram.volapp.views import (
    index_view,
    explore_view,
    dashboard_view,
    groups,
    members,
)

urlpatterns = [
    url('^', index_view, name='index'),
    url(r'^dashboard/$', dashboard_view, name='dashboard'),
    url(r'^explore/$', explore_view, name='explore'),
]

# Groups
urlpatterns += [
    url(r'^groups/$', groups.group_list, name='group_list'),
    url(r'^groups/(?P<pk>\w+)/$', groups.group_detail, name='group_detail'),
    url(r'^groups/create/$', groups.create_group, name='group_create'),
    url(r'^groups/delete/$', groups.delete_group, name='group_delete'),
]

# Members
urlpatterns += [
    url(r'^groups/(?P<pk>\w+)/members/$', groups.group_member_list, name='group_member_list'),
    url(r'^members/(?P<pk>\w+)/$', groups.group_member_detail, name='group_member_detail'),
    url(r'^groups/members/create/$', groups.group_member_add, name='group_member_add'),
    url(r'^groups/members/delete/$', groups.group_member_delete, name='group_member_delete'),
    url(r'^groups/members/$', groups.group_member_edit_list, name='group_member_edit_list'),
    url(r'^groups/members/(?P<pk>\w+)/edit$', groups.group_member_edit_detail, name='group_member_edit_list'),
]

# Api
urlpatterns += [
    #url(r'^api-view/volunteers/$', volunteers.json_view, name="volunteers_json"),
    url(r'^api-view/groups/$', groups.json_view, name="groups_json"),
]

marjoram/orgapp/forms/contact.py
from django import forms
from django.forms.formsets import formset_factory
from django.forms.extras import widgets
from django.contrib.admin import widgets as admin_widgets
from django.core.exceptions import ValidationError
from marjoram.orgapp import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User, Group, Permission


class ContactForm(forms.Form):
    username = forms.EmailField(label=_("Email"),
                            max_length=75,
                            widget=forms.TextInput(attrs={'class': 'form-control'}))
    subject = forms.ChoiceField(
        required=True,
        choices=(
            ('question', 'Question'),
            ('problem', 'Problem'),
            ('suggestion', "Suggestion"),
            ('other', 'Other Issue')
        )
    )
    message = forms.CharField(
        required=False, label=_("Message"), max_length=1000, min_length=5,
        widget=forms.widgets.Textarea(attrs={'class': 'form-control'})
    )

marjoram/orgapp/forms/create_organization.py
from django.forms import ModelForm
from marjoram.orgapp.models import Organization

class CreateOrganizationForm(ModelForm):
    class Meta:
        model = Organization
        fields = ['name', 'description', 'phone', 'email', 'address', 'max_volunteers', 'min_volunteers']

marjoram/orgapp/forms/organization.py
from django import forms
from django.forms.formsets import formset_factory
from django.forms.extras import widgets
from django.contrib.admin import widgets as admin_widgets
from django.core.exceptions import ValidationError
from marjoram.orgapp import models
from django.conf import settings
from django.core.urlresolvers import reverse
from django.utils.translation import ugettext_lazy as _
from django.contrib.auth.models import User, Group, Permission



class OrganizationFilterForm(forms.Form):

    ORGANIZATION_TYPE_CHOICES = (
        ('', '----------'),
    ) + models.Organization.ORGANIZATION_TYPE_CHOICES

    org_type = forms.ChoiceField(
        required=False,
        choices=ORGANIZATION_TYPE_CHOICES,
    )
    pk = forms.IntegerField(
        label='',
        required=False,
        widget=forms.HiddenInput,
    )

    def __init__(self, *args, **kwargs):
        super(OrganizationFilterForm, self).__init__(*args, **kwargs)
        for key, value in self.fields.iteritems():
            self.fields[key].widget.attrs['class'] = 'form-control'

    def get_organizations(self, initial_qs=None):
        ''' retrieve organizations matching the criteria'''
        if self.errors:
            return models.Organization.objects.none()

        qs = models.Organization.objects.all() if not initial_qs else initial_qs
        data = self.cleaned_data
        if data.get('pk'):
            qs = qs.filter(pk=data['pk'])

        return qs.distinct()

class StateOrganizationForm(forms.Form):
    """Set volunteering as open/close and
    display the min and max volunteers
    """
    pass

marjoram/orgapp/views/organizations.py
from django.views.generic import ListView, DetailView, TemplateView, FormView, CreateView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from . import NameSearchMixin
from marjoram.orgapp.models import Organization
from marjoram.orgapp.forms import CreateOrganizationForm, ContactForm, OrganizationFilterForm


class CreateOrganizationView(FormView):
    template_name = 'org/create_organization.html'
    form_class = CreateOrganizationForm
    success_url = '/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        return super(CreateOrganizationForm, self).form_valid(form)

    @method_decorator(login_required)
    def dispatch(self, request, *args, **kwargs):
        return super(CreateOrganizationView, self).dispatch(request, *args, **kwargs)

    def post(self, request, pk=None, *args, **kwargs):
        if pk:
            self.org_inst = get_object_or_404(Organization, pk=pk)
            self.template_name = 'org/organization_settings.html'
        else:
            self.org_inst = Organization(creator=self.request.user)
        self.org_form = CreateOrganizationForm(
            user=self.request.user,
            instance=self.org_inst,
            data=request.POST
        )

        if self.org_form.is_valid():
            data = self.org_form.cleaned_data
            data['creator'] = request.user

        return redirect(
            'organization_profile',
            pk=organization.pk,
        )
        return self.get(request, *args, **kwargs)


class OrganizationDelete(DetailView):
    model = Organization
    success_url = reverse_lazy('list_organization')


class UpdateOrganizationView(UpdateView):

    model = Organization
    form_class = CreateOrganizationForm
    template_name = 'org/organization_settings.html'
    success_url = 'organization_profile'

class OrganizationDetailView(DetailView):
    template_name = 'org/organization_detail.html'
    model = Organization


class ContactOrganizationView(FormView):
    template_name = 'org/contact.html'
    form_class = ContactForm
    success_url = 'org/thanks/'

    def form_valid(self, form):
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        #form.send_email()
        return super(ContactView, self).form_valid(form)


class OrganizationListView(NameSearchMixin, ListView):
    template_name = 'org/organization_list.html'
    paginate_by = 10
    model = Organization

    def dispatch(self, *args, **kwargs):
        return super(OrganizationListView, self).dispatch(*args, **kwargs)

    def get_queryset(self):
        qs = super(OrganizationListView, self).get_queryset()
        form = OrganizationFilterForm(self.request.GET)
        if form.is_valid():
            return form.get_organizations(qs)

        return Organization.objects.none()

    def get_context_data(self, **kwargs):
        context = super(OrganizationListView, self).get_context_data(**kwargs)
        initial = self.request.GET.copy()
        context.update({
            'form': OrganizationFilterForm(initial=initial),
        })
        return context

organization_add_view = CreateOrganizationView.as_view()
organization_delete_view = OrganizationDelete.as_view()
organization_contact_view = ContactOrganizationView.as_view()
organization_detail_view = OrganizationDetailView.as_view()
organization_list_view = OrganizationListView.as_view()
organization_settings_view = UpdateOrganizationView.as_view()
#sorganization_json_view = OrganizationJsonView.as_view()

marjoram/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

marjoram/volapp/views/groups.py
from django.views.generic import DetailView, View, ListView, TemplateView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from marjoram.volapp import models
from . import JsonView


class GroupCreateView(CreateView):
    model = models.Group
    fields = []
    template_name = 'vol/create_group.html'

class GroupProfileView(DetailView):
    model = models.Group
    template_name = 'vol/group_detail.html'

class GroupDeleteView(TemplateView):
    pass

class EditGroupView(UpdateView):
    model = models.Group
    template_name = 'vol/group_settings.html'        

# Admin
class GroupListView(ListView):
    template_name = 'vol/group_list.html'
    model = models.Group
    paginate_by = 10

class GroupMemberListView(ListView):
    pass

class GroupMemberAddView(TemplateView):
    pass

class GroupMemberDetailView(DetailView):
    pass

class GroupMemberDeleteView(TemplateView):
    pass

class GroupMemberEditListView(ListView):
    pass

class GroupMemberEditDetailView(UpdateView):
    pass


group_member_list = GroupMemberListView.as_view()
group_member_add = GroupMemberAddView.as_view()
group_member_delete = GroupMemberDeleteView.as_view()
group_member_detail = GroupMemberDetailView.as_view()
group_member_edit_list = GroupMemberEditListView.as_view()
group_member_edit_detail = GroupMemberEditDetailView.as_view()
group_list = GroupListView.as_view()
group_detail = GroupProfileView.as_view()
group_settings = EditGroupView.as_view()
create_group = GroupCreateView.as_view()
delete_group = GroupDeleteView.as_view()


class GroupAPI(JsonView):

    status = 200
    ACTIONS = (
        'search_groups'
    )

    # @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        self.member = False
        return super(GroupAPI, self).dispatch(*args, **kwargs)

    @property
    def default_group_list(self):
        return models.volunteer.Volunteer.objects.get.all()

    def _build_json(self, users, errors, success=True):
        json_dict = {
            'errors': errors,
            'groups': [],
            'success': success
        }
        for group in groups:
            json_dict['groups'].append({
                'name': models.volunteer.Volunteer.objects.get('name'),
            })

            return json_dict

    def _filter_users_by_name(self, users, name):
        return users.filter(
            Q(username__icontains=name) |
            Q(userprofile__display_name__icontains=name)
        )

    def _search_users(self, post_data):
        name = post_data.get('name')
        users = self._filter_users_by_name(
            self.default_volunteer_list,
            name
        )
        return self._build_json(users, {})

    def post(self, *args, **kwargs):
        post_data = self.request.POST.copy()
        action = post_data.get('action')
        if action in self.ACTIONS:
            return getattr(self, '_{}'.format(action))(post_data)

        self.status = 400
        return {
            'errors': {'action': 'Invalid Action'},
            'groups': [],
            'success': False
        }

json_view = GroupAPI.as_view()

marjoram/volapp/views/members.py
from django.views.generic import DetailView, ListView
from marjoram.volapp import models

class MemberListView(ListView):
    template_name = 'org/member_list.html'
    paginate_by = 10

member_list = MemberListView.as_view()

marjoram/templates/vol/create_group.html
{% extends "base.html" %}

{% block content %}
    <h1>test</h1>
{% endblock %}

marjoram/templates/vol/dashboard.html
{% extends 'base.html' %}

marjoram/templates/vol/explore.html
{% extends 'base.html' %}

{% block content %}
<link href="/static/css/album.css" rel="stylesheet">

<script src="/static/library/holder.min.js"></script>

   <div class="album text-muted">
     <div class="container">
       <h1>Groups</h1>
    {% for obj in object_list %}
       <div class="row">
         <div class="card">
           <img data-src="holder.js/100px280/thumb" alt="Card image cap">
           <p class="card-text">{{ obj.description }} <a href="{% url 'group-profile' pk=obj.pk %}">View Profile</a>.</p>
   </div>
   {% endfor %}


         <h1>Organizations</h1>
         <div class="card">
           <img data-src="holder.js/100px280/thumb" alt="Card image cap">
           <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
         </div>
         <div class="card">
           <img data-src="holder.js/100px280/thumb" alt="Card image cap">
           <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
         </div>
         <div class="card">
           <img data-src="holder.js/100px280/thumb" alt="Card image cap">
           <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
         </div>
       </div>

     </div>
   </div>
{% endblock %}

marjoram/templates/vol/group_detail.html
{% extends 'base.html' %}
{% block content %}
Phone: {{ object.phone }}
Username: {{ object.description }}
Email: {{ object.email }}
<a href="{% url 'group-manage' pk=object.pk %}">Edit profile</a>

{% endblock %}

marjoram/templates/vol/group_list.html
{% extends 'base.html' %}

{% block content %}

<section class="jumbotron text-xs-center">
     <div class="container">
       <h1 class="jumbotron-heading">Album example</h1>
       <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p>
       <p>
         <a href="#" class="btn btn-primary">Main call to action</a>
         <a href="#" class="btn btn-secondary">Secondary action</a>
       </p>
     </div>
   </section>

   <div class="album text-muted">
     <div class="container">

       <div class="row">
         <div class="card">
           <img data-src="holder.js/100px280/thumb" alt="Card image cap">
           <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
         </div>
         <div class="card">
           <img data-src="holder.js/100px280/thumb" alt="Card image cap">
           <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
         </div>
         <div class="card">
           <img data-src="holder.js/100px280/thumb" alt="Card image cap">
           <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
         </div>

         <div class="card">
           <img data-src="holder.js/100px280/thumb" alt="Card image cap">
           <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
         </div>
         <div class="card">
           <img data-src="holder.js/100px280/thumb" alt="Card image cap">
           <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
         </div>
         <div class="card">
           <img data-src="holder.js/100px280/thumb" alt="Card image cap">
           <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
         </div>

         <div class="card">
           <img data-src="holder.js/100px280/thumb" alt="Card image cap">
           <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
         </div>
         <div class="card">
           <img data-src="holder.js/100px280/thumb" alt="Card image cap">
           <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
         </div>
         <div class="card">
           <img data-src="holder.js/100px280/thumb" alt="Card image cap">
           <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
         </div>
       </div>

     </div>
   </div>
{% endblock %}

marjoram/templates/vol/group_settings.html
{% extends 'base.html' %}

marjoram/templates/vol/index.html
{% extends 'base.html' %}

{% block content %}

<div class="row">
  <div class="col-md-8">
    <h3>Your Organizations as a volunteer!</h3>
    <p>Some info about this GUI here! Wow, all you need now is an account!</p>
    <br>
  </div>
    <div class="col-md-4">
      <h3 href="#">Information </h3>
      <br>
      <p> here's some contact info or something regarding
        how great the marjoram suite is, and a link to the real shit, marvol
        </p>

        <div class="list-group">
          <a href="{% url 'volapp:explore' %}" class="list-group-item">Explore</a>
          <a href="{% url 'volapp:group_list' %}" class="list-group-item">Groups</a>
          <a href="{% url 'volapp:group_create' %}" class="list-group-item">Create Group</a>
        </div>

        <p>You can also edit the group, volunteer list WIP</p>

    </div> {# column div #}
</div>
{% endblock %}

marjoram/templates/vol/manage_group.html
{% extends 'base.html' %}

marjoram/templates/vol/manage_group_admins.html
{% extends 'base.html' %}

marjoram/templates/vol/member_list.html
{% extends 'base.html' %}